### ISSUE TITLE
license问题

### ISSUE THREAD

**Issue by kongdd** [bubifengyun/SJTUThesis-Rmd#7]
您好：

1. 昨天贴的问题已经解决了。我发现 tinytex更新package之后，就不能编译了。果断弃用，采用miktex，最终又正确编译出来了。

2. 我想用您的模板，做一个中山大学的博士论文模板，请问可以发布在github上吗？license有啥要注意的吗？

感谢！

**Comment by bubifengyun** [comment]
我去，没有考虑过。交大模板的apache license，别人的东西还是保留吧。我这边怎么弄就可以，方便的话，在致谢里给留个链接就可以啦。非常感谢你这么强的版权意识，欢迎传播。

**Comment by kongdd** [comment]
OK
